# Generated by Django 5.0.7 on 2024-09-19 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_dishes', to='dishes.dish')),
                ('ingredients', models.ManyToManyField(blank=True, to='dishes.recipeingredient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_dishes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_dishes',
            },
        ),
    ]
