# Generated by Django 5.0.7 on 2024-10-04 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0004_alter_dish_images'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCreatedDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('images', models.ImageField(blank=True, null=True, upload_to='user_dish_image/')),
                ('category', models.CharField(max_length=50, null=True)),
                ('recipes', models.TextField(null=True)),
                ('products', models.ManyToManyField(blank=True, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_created_dishes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_created_dishes',
            },
        ),
        migrations.CreateModel(
            name='UserCreatedDishProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dishes.usercreateddish')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'user_created_dish_products',
                'unique_together': {('dish', 'product')},
            },
        ),
    ]
