# Generated by Django 5.0.7 on 2024-09-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('images', models.CharField(max_length=255, null=True)),
                ('text', models.TextField(null=True)),
                ('proteins', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fats', models.DecimalField(decimal_places=2, max_digits=5)),
                ('carbs', models.DecimalField(decimal_places=2, max_digits=5)),
                ('kcals', models.DecimalField(decimal_places=2, max_digits=5)),
                ('categorys', models.CharField(max_length=50, null=True)),
                ('areas', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
