# Generated by Django 5.0.7 on 2024-10-18 12:22

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.user_profile_image_path, verbose_name='Аватар'),
        ),
    ]
